baseURL = "/"
copyright = "Nava Solutions | All Rights Reserved"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Nava Solutions"

FootnoteReturnLinkContents = "↩"
SectionPagesMenu = "main"

[permalinks]
  blog = "/:title/"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  OpenLinksInNewWindow = true

[params.soclial]
  facebook = "NavaSolns"
  twitter = "nava_solutions"
  linkedin = "nava-solutions"

[params.google]
  analytics = ""

[params.meta]
  description = "Nava Solutions is committed to develop software applications which accelerate the adoption of cloud solutions in a secure manner. The Nava Solutions software team produces solid, high-level and professional products which are easy to use at the same time."
  keywords = "nava,nava solutions,cloud,security,linkgard,nava siem,navacertus"

[outputs]
  home = ["html"]