baseURL = "https://nava-solutions.netlify.com/"
copyright = "Nava Solutions | All Rights Reserved"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Nava Solutions"

FootnoteReturnLinkContents = "↩"
SectionPagesMenu = "main"

[permalinks]
  blog = "/blog/:filename/"
  events = "/events/:year/:month/:title/"
  news = "/news/:filename/"
  category = "/blog/category/:slug/"

[taxonomies]
  category = "category"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  OpenLinksInNewWindow = true
  description = "Nava Solutions is committed to develop software applications which accelerate the adoption of cloud solutions in a secure manner. The Nava Solutions software team produces solid, high-level and professional products which are easy to use at the same time."
  keywords = "nava,nava solutions,cloud,security,linkgard,nava siem,navacertus"

[params.social]
  facebook = "NavaSolns"
  twitter = "nava_solutions"
  linkedin = "nava-solutions"

[params.google]
  analytics = "UA-41226205-1"

[outputs]
  home = ["html"]