[context.production.environment]
  HUGO_VERSION = "0.54"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.54"

[context.branch-deploy]
  HUGO_VERSION = "0.54"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' *.netlify.com *.cloudfront.net *.wufoo.com data:; style-src 'unsafe-inline' 'self' *.netlify.com"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"