[build]
  publish = "public"
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.53"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.53"
  HUGO_ENV = "development"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' *.netlify.com *.cloudfront.net *.wufoo.com data:; style-src 'nonce-99siuh1um48oe63w6ftunmec' 'self' *.netlify.com; script-src 'nonce-99siuh1um48oe63w6ftunmec' 'self' www.google-analytics.com *.wufoo.com"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"